# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 310, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(83, 310, 16, 16))
        self.label_5.setObjectName("label_5")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(105, 310, 44, 23))
        self.lcdNumber_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(155, 310, 16, 16))
        self.label_6.setObjectName("label_6")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(177, 310, 44, 23))
        self.lcdNumber_3.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(11, 370, 105, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(11, 401, 105, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(11, 438, 90, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(11, 475, 60, 16))
        self.label_11.setObjectName("label_11")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(123, 401, 91, 23))
        self.lcdNumber_7.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setGeometry(QtCore.QRect(123, 438, 91, 23))
        self.lcdNumber_8.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setGeometry(QtCore.QRect(123, 475, 91, 23))
        self.lcdNumber_9.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.label_0 = QtWidgets.QLabel(self.centralwidget)
        self.label_0.setGeometry(QtCore.QRect(10, -11, 241, 571))
        self.label_0.setStyleSheet("background-color:rgb(218, 218, 218)")
        self.label_0.setText("")
        self.label_0.setObjectName("label_0")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(123, 370, 91, 21))
        self.lineEdit_1.setStyleSheet("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(0, 10, 261, 141))
        self.label_1.setStyleSheet("image: url(:/logo.jpg);")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(11, 260, 60, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(11, 230, 111, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(11, 200, 111, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 290, 60, 16))
        self.label_17.setObjectName("label_17")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 340, 16, 16))
        self.label_8.setObjectName("label_8")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(105, 340, 44, 23))
        self.lcdNumber_5.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(83, 340, 16, 16))
        self.label_18.setObjectName("label_18")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(32, 340, 45, 23))
        self.lcdNumber_4.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(177, 340, 44, 23))
        self.lcdNumber_6.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(155, 340, 16, 16))
        self.label_19.setObjectName("label_19")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(133, 161, 52, 28))
        self.pushButton_3.setStyleSheet("background-color: rgb(9, 200, 229);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lcdNumber_1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_1.setGeometry(QtCore.QRect(32, 310, 45, 23))
        self.lcdNumber_1.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(11, 505, 75, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(123, 505, 91, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(15, 161, 52, 28))
        self.pushButton_1.setStyleSheet("background-color: rgb(9, 200, 229);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(74, 161, 52, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(9, 200, 229);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(192, 161, 52, 28))
        self.pushButton_4.setStyleSheet("background-color: rgb(9, 200, 229);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 0, 541, 561))
        self.label.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 200, 16, 16))
        self.label_2.setStyleSheet("image: url(:/light_white.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 230, 16, 16))
        self.label_3.setStyleSheet("image: url(:/light_white.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(150, 260, 16, 16))
        self.label_12.setStyleSheet("image: url(:/light_white.jpg);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(180, 260, 16, 16))
        self.label_20.setStyleSheet("image: url(:/light_white.jpg);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(210, 260, 16, 16))
        self.label_21.setStyleSheet("image: url(:/light_white.jpg);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_0.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.lcdNumber_2.raise_()
        self.label_6.raise_()
        self.lcdNumber_3.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.lcdNumber_7.raise_()
        self.lcdNumber_8.raise_()
        self.lcdNumber_9.raise_()
        self.lineEdit_1.raise_()
        self.label_1.raise_()
        self.pushButton_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_1.raise_()
        self.lcdNumber_1.raise_()
        self.label_13.raise_()
        self.lineEdit_2.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_8.raise_()
        self.lcdNumber_5.raise_()
        self.label_18.raise_()
        self.lcdNumber_4.raise_()
        self.lcdNumber_6.raise_()
        self.label_19.raise_()
        self.pushButton_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_12.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "视比特机器人包裹分拣系统视觉软件"))
        self.label_4.setText(_translate("MainWindow", "x:"))
        self.label_5.setText(_translate("MainWindow", "y:"))
        self.label_6.setText(_translate("MainWindow", "z:"))
        self.label_7.setText(_translate("MainWindow", "机器人运转情况"))
        self.label_9.setText(_translate("MainWindow", "已处置商品数量"))
        self.label_10.setText(_translate("MainWindow", "异常情况次数"))
        self.label_11.setText(_translate("MainWindow", "运行时间"))
        self.label_14.setText(_translate("MainWindow", "吸盘状态"))
        self.label_15.setText(_translate("MainWindow", "读码器连接状态"))
        self.label_16.setText(_translate("MainWindow", "相机连接状态"))
        self.label_17.setText(_translate("MainWindow", "抓取坐标"))
        self.label_8.setText(_translate("MainWindow", "a:"))
        self.label_18.setText(_translate("MainWindow", "b:"))
        self.label_19.setText(_translate("MainWindow", "c:"))
        self.pushButton_3.setText(_translate("MainWindow", "返回"))
        self.label_13.setText(_translate("MainWindow", "条形码信息"))
        self.pushButton_1.setText(_translate("MainWindow", "开始"))
        self.pushButton_2.setText(_translate("MainWindow", "停止"))
        self.pushButton_4.setText(_translate("MainWindow", "复位"))
import picture_rc
